/**
 * Map class contains methods to return custom map for each Location
 * 
 * @author Amelia
 * TODO (Pre-push: Update version)
 * @version 0.21
 */
public class Map {
    /**
     * All of the methods within this class print the associated location's map when
     * called from the player menu option.
     * 
     * @return
     */
    public static String a1Map() {
        return String.join("\n", "                             Hero's Map                                     ",
                "|--------------|--------------|--------------|--------------|--------------|",
                "|              |              |                             |              |",
                "|    Castle                  [X]   [The Counts Chamber]        The Throne  |",
                "|    Armoury                 [X]                                  Room     |",
                "|<You Are Here>|              |                             |              |",
                "|--------------|-            -|--------------|--------------|--------------|",
                "|                             |              |              |//////////////|",
                "|    [Castle Sinistraad]      |   Duskwood   |    Mystic    |////Twisted///|",
                "|                             |   Clearing   |    Lake      |///Mountains//|",
                "|                             |              |              |//////////////|",
                "|-            -|----      ----|-            -|-            -|--------------|",
                "|              |              |                             |              |",
                "|              |    Castle    |                             |   Twisted    |",
                "|              |    Cellar    |                             |    Caves     |",
                "|              |              |                             |              |",
                "|----[X][X]----|--------------|--------------|-            -|-            -|",
                "|                                                           |              |",
                "|    Castle              [Duskwood Forest]                 [X]   Tilled    |",
                "|   Courtyard                                              [X]   Plains    |",
                "|                                                           |              |",
                "|--------------|-            -|--------------|-            -|-            -|",
                "|//////////////|                             |              |              |",
                "|///Endless////|                   Wolves    |              |     Old      |",
                "|//// Fog//////|                    Den      |              |     Town     |",
                "|//////////////|                             |              |              |",
                "|--------------|--------------|--------------|--------------|--------------|");
    }

    public static String a2Map() {
        return String.join("\n", "                             Hero's Map                                     ",
                "|--------------|--------------|--------------|--------------|--------------|",
                "|              |              |                             |              |",
                "|    Castle                  [X]   [The Counts Chamber]        The Throne  |",
                "|    Armoury                 [X]                                  Room     |",
                "|              |              |                             |              |",
                "|--------------|-            -|--------------|--------------|--------------|",
                "|                             |              |              |//////////////|",
                "|    [Castle Sinistraad]      |   Duskwood   |    Mystic    |////Twisted///|",
                "|                             |   Clearing   |    Lake      |///Mountains//|",
                "|<You Are Here>               |              |              |//////////////|",
                "|-            -|----      ----|-            -|-            -|--------------|",
                "|              |              |                             |              |",
                "|              |    Castle    |                             |   Twisted    |",
                "|              |    Cellar    |                             |    Caves     |",
                "|              |              |                             |              |",
                "|----[X][X]----|--------------|--------------|-            -|-            -|",
                "|                                                           |              |",
                "|    Castle              [Duskwood Forest]                 [X]   Tilled    |",
                "|   Courtyard                                              [X]   Plains    |",
                "|                                                           |              |",
                "|--------------|-            -|--------------|-            -|-            -|",
                "|//////////////|                             |              |              |",
                "|///Endless////|                   Wolves    |              |     Old      |",
                "|//// Fog//////|                    Den      |              |     Town     |",
                "|//////////////|                             |              |              |",
                "|--------------|--------------|--------------|--------------|--------------|");
    }

    public static String a3Map() {
        return String.join("\n", "                             Hero's Map                                     ",
                "|--------------|--------------|--------------|--------------|--------------|",
                "|              |              |                             |              |",
                "|    Castle                  [X]   [The Counts Chamber]        The Throne  |",
                "|    Armoury                 [X]                                  Room     |",
                "|              |              |                             |              |",
                "|--------------|-            -|--------------|--------------|--------------|",
                "|                             |              |              |//////////////|",
                "|    [Castle Sinistraad]      |   Duskwood   |    Mystic    |////Twisted///|",
                "|                             |   Clearing   |    Lake      |///Mountains//|",
                "|                             |              |              |//////////////|",
                "|-            -|----      ----|-            -|-            -|--------------|",
                "|              |              |                             |              |",
                "|              |    Castle    |                             |   Twisted    |",
                "|              |    Cellar    |                             |    Caves     |",
                "|<You Are Here>|              |                             |              |",
                "|----[X][X]----|--------------|--------------|-            -|-            -|",
                "|                                                           |              |",
                "|    Castle              [Duskwood Forest]                 [X]   Tilled    |",
                "|   Courtyard                                              [X]   Plains    |",
                "|                                                           |              |",
                "|--------------|-            -|--------------|-            -|-            -|",
                "|//////////////|                             |              |              |",
                "|///Endless////|                   Wolves    |              |     Old      |",
                "|//// Fog//////|                    Den      |              |     Town     |",
                "|//////////////|                             |              |              |",
                "|--------------|--------------|--------------|--------------|--------------|");
    }

    public static String a4Map() {
        return String.join("\n", "                             Hero's Map                                     ",
                "|--------------|--------------|--------------|--------------|--------------|",
                "|              |              |                             |              |",
                "|    Castle                  [X]   [The Counts Chamber]        The Throne  |",
                "|    Armoury                 [X]                                  Room     |",
                "|              |              |                             |              |",
                "|--------------|-            -|--------------|--------------|--------------|",
                "|                             |              |              |//////////////|",
                "|    [Castle Sinistraad]      |   Duskwood   |    Mystic    |////Twisted///|",
                "|                             |   Clearing   |    Lake      |///Mountains//|",
                "|                             |              |              |//////////////|",
                "|-            -|----      ----|-            -|-            -|--------------|",
                "|              |              |                             |              |",
                "|              |    Castle    |                             |   Twisted    |",
                "|              |    Cellar    |                             |    Caves     |",
                "|              |              |                             |              |",
                "|----[X][X]----|--------------|--------------|-            -|-            -|",
                "|                                                           |              |",
                "|    Castle              [Duskwood Forest]                 [X]   Tilled    |",
                "|   Courtyard                                              [X]   Plains    |",
                "|<You Are Here>                                             |              |",
                "|--------------|-            -|--------------|-            -|-            -|",
                "|//////////////|                             |              |              |",
                "|///Endless////|                   Wolves    |              |     Old      |",
                "|//// Fog//////|                    Den      |              |     Town     |",
                "|//////////////|                             |              |              |",
                "|--------------|--------------|--------------|--------------|--------------|");
    }

    public static String b1Map() {
        return String.join("\n", "                             Hero's Map                                     ",
                "|--------------|--------------|--------------|--------------|--------------|",
                "|              |              |                             |              |",
                "|    Castle                  [X]   [The Counts Chamber]        The Throne  |",
                "|    Armoury                 [X]                                  Room     |",
                "|              |<You Are Here>|                             |              |",
                "|--------------|-            -|--------------|--------------|--------------|",
                "|                             |              |              |//////////////|",
                "|    [Castle Sinistraad]      |   Duskwood   |    Mystic    |////Twisted///|",
                "|                             |   Clearing   |    Lake      |///Mountains//|",
                "|                             |              |              |//////////////|",
                "|-            -|----      ----|-            -|-            -|--------------|",
                "|              |              |                             |              |",
                "|              |    Castle    |                             |   Twisted    |",
                "|              |    Cellar    |                             |    Caves     |",
                "|              |              |                             |              |",
                "|----[X][X]----|--------------|--------------|-            -|-            -|",
                "|                                                           |              |",
                "|    Castle              [Duskwood Forest]                 [X]   Tilled    |",
                "|   Courtyard                                              [X]   Plains    |",
                "|                                                           |              |",
                "|--------------|-            -|--------------|-            -|-            -|",
                "|//////////////|                             |              |              |",
                "|///Endless////|                   Wolves    |              |     Old      |",
                "|//// Fog//////|                    Den      |              |     Town     |",
                "|//////////////|                             |              |              |",
                "|--------------|--------------|--------------|--------------|--------------|");
    }

    public static String b2Map() {
        return String.join("\n", "                             Hero's Map                                     ",
                "|--------------|--------------|--------------|--------------|--------------|",
                "|              |              |                             |              |",
                "|    Castle                  [X]   [The Counts Chamber]        The Throne  |",
                "|    Armoury                 [X]                                  Room     |",
                "|              |              |                             |              |",
                "|--------------|-            -|--------------|--------------|--------------|",
                "|                             |              |              |//////////////|",
                "|    [Castle Sinistraad]      |   Duskwood   |    Mystic    |////Twisted///|",
                "|                             |   Clearing   |    Lake      |///Mountains//|",
                "|               <You Are Here>|              |              |//////////////|",
                "|-            -|----      ----|-            -|-            -|--------------|",
                "|              |              |                             |              |",
                "|              |    Castle    |                             |   Twisted    |",
                "|              |    Cellar    |                             |    Caves     |",
                "|              |              |                             |              |",
                "|----[X][X]----|--------------|--------------|-            -|-            -|",
                "|                                                           |              |",
                "|    Castle              [Duskwood Forest]                 [X]   Tilled    |",
                "|   Courtyard                                              [X]   Plains    |",
                "|                                                           |              |",
                "|--------------|-            -|--------------|-            -|-            -|",
                "|//////////////|                             |              |              |",
                "|///Endless////|                   Wolves    |              |     Old      |",
                "|//// Fog//////|                    Den      |              |     Town     |",
                "|//////////////|                             |              |              |",
                "|--------------|--------------|--------------|--------------|--------------|");
    }

    public static String b3Map() {
        return String.join("\n", "                             Hero's Map                                     ",
                "|--------------|--------------|--------------|--------------|--------------|",
                "|              |              |                             |              |",
                "|    Castle                  [X]   [The Counts Chamber]        The Throne  |",
                "|    Armoury                 [X]                                  Room     |",
                "|              |              |                             |              |",
                "|--------------|-            -|--------------|--------------|--------------|",
                "|                             |              |              |//////////////|",
                "|    [Castle Sinistraad]      |   Duskwood   |    Mystic    |////Twisted///|",
                "|                             |   Clearing   |    Lake      |///Mountains//|",
                "|                             |              |              |//////////////|",
                "|-            -|----      ----|-            -|-            -|--------------|",
                "|              |              |                             |              |",
                "|              |    Castle    |                             |   Twisted    |",
                "|              |    Cellar    |                             |    Caves     |",
                "|              |<You Are Here>|                             |              |",
                "|----[X][X]----|--------------|--------------|-            -|-            -|",
                "|                                                           |              |",
                "|    Castle              [Duskwood Forest]                 [X]   Tilled    |",
                "|   Courtyard                                              [X]   Plains    |",
                "|                                                           |              |",
                "|--------------|-            -|--------------|-            -|-            -|",
                "|//////////////|                             |              |              |",
                "|///Endless////|                   Wolves    |              |     Old      |",
                "|//// Fog//////|                    Den      |              |     Town     |",
                "|//////////////|                             |              |              |",
                "|--------------|--------------|--------------|--------------|--------------|");
    }

    public static String b4Map() {
        return String.join("\n", "                             Hero's Map                                     ",
                "|--------------|--------------|--------------|--------------|--------------|",
                "|              |              |                             |              |",
                "|    Castle                  [X]   [The Counts Chamber]        The Throne  |",
                "|    Armoury                 [X]                                  Room     |",
                "|              |              |                             |              |",
                "|--------------|-            -|--------------|--------------|--------------|",
                "|                             |              |              |//////////////|",
                "|    [Castle Sinistraad]      |   Duskwood   |    Mystic    |////Twisted///|",
                "|                             |   Clearing   |    Lake      |///Mountains//|",
                "|                             |              |              |//////////////|",
                "|-            -|----      ----|-            -|-            -|--------------|",
                "|              |              |                             |              |",
                "|              |    Castle    |                             |   Twisted    |",
                "|              |    Cellar    |                             |    Caves     |",
                "|              |              |                             |              |",
                "|----[X][X]----|--------------|--------------|-            -|-            -|",
                "|                                                           |              |",
                "|    Castle              [Duskwood Forest]                 [X]   Tilled    |",
                "|   Courtyard                                              [X]   Plains    |",
                "|               <You Are Here>                              |              |",
                "|--------------|-            -|--------------|-            -|-            -|",
                "|//////////////|                             |              |              |",
                "|///Endless////|                   Wolves    |              |     Old      |",
                "|//// Fog//////|                    Den      |              |     Town     |",
                "|//////////////|                             |              |              |",
                "|--------------|--------------|--------------|--------------|--------------|");
    }

    public static String b5Map() {
        return String.join("\n", "                             Hero's Map                                     ",
                "|--------------|--------------|--------------|--------------|--------------|",
                "|              |              |                             |              |",
                "|    Castle                  [X]   [The Counts Chamber]        The Throne  |",
                "|    Armoury                 [X]                                  Room     |",
                "|              |              |                             |              |",
                "|--------------|-            -|--------------|--------------|--------------|",
                "|                             |              |              |//////////////|",
                "|    [Castle Sinistraad]      |   Duskwood   |    Mystic    |////Twisted///|",
                "|                             |   Clearing   |    Lake      |///Mountains//|",
                "|                             |              |              |//////////////|",
                "|-            -|----      ----|-            -|-            -|--------------|",
                "|              |              |                             |              |",
                "|              |    Castle    |                             |   Twisted    |",
                "|              |    Cellar    |                             |    Caves     |",
                "|              |              |                             |              |",
                "|----[X][X]----|--------------|--------------|-            -|-            -|",
                "|                                                           |              |",
                "|    Castle              [Duskwood Forest]                 [X]   Tilled    |",
                "|   Courtyard                                              [X]   Plains    |",
                "|                                                           |              |",
                "|--------------|-            -|--------------|-            -|-            -|",
                "|//////////////|                             |              |              |",
                "|///Endless////|                   Wolves    |              |     Old      |",
                "|//// Fog//////|                    Den      |              |     Town     |",
                "|//////////////|<You Are Here>               |              |              |",
                "|--------------|--------------|--------------|--------------|--------------|");
    }

    public static String c1Map() {
        return String.join("\n", "                             Hero's Map                                     ",
                "|--------------|--------------|--------------|--------------|--------------|",
                "|              |              |                             |              |",
                "|    Castle                  [X]   [The Counts Chamber]        The Throne  |",
                "|    Armoury                 [X]                                  Room     |",
                "|              |              |<You Are Here>               |              |",
                "|--------------|-            -|--------------|--------------|--------------|",
                "|                             |              |              |//////////////|",
                "|    [Castle Sinistraad]      |   Duskwood   |    Mystic    |////Twisted///|",
                "|                             |   Clearing   |    Lake      |///Mountains//|",
                "|                             |              |              |//////////////|",
                "|-            -|----      ----|-            -|-            -|--------------|",
                "|              |              |                             |              |",
                "|              |    Castle    |                             |   Twisted    |",
                "|              |    Cellar    |                             |    Caves     |",
                "|              |              |                             |              |",
                "|----[X][X]----|--------------|--------------|-            -|-            -|",
                "|                                                           |              |",
                "|    Castle              [Duskwood Forest]                 [X]   Tilled    |",
                "|   Courtyard                                              [X]   Plains    |",
                "|                                                           |              |",
                "|--------------|-            -|--------------|-            -|-            -|",
                "|//////////////|                             |              |              |",
                "|///Endless////|                   Wolves    |              |     Old      |",
                "|//// Fog//////|                    Den      |              |     Town     |",
                "|//////////////|                             |              |              |",
                "|--------------|--------------|--------------|--------------|--------------|");
    }

    public static String c2Map() {
        return String.join("\n", "                             Hero's Map                                     ",
                "|--------------|--------------|--------------|--------------|--------------|",
                "|              |              |                             |              |",
                "|    Castle                  [X]   [The Counts Chamber]        The Throne  |",
                "|    Armoury                 [X]                                  Room     |",
                "|              |              |                             |              |",
                "|--------------|-            -|--------------|--------------|--------------|",
                "|                             |              |              |//////////////|",
                "|    [Castle Sinistraad]      |   Duskwood   |    Mystic    |////Twisted///|",
                "|                             |   Clearing   |    Lake      |///Mountains//|",
                "|                             |<You Are Here>|              |//////////////|",
                "|-            -|----      ----|-            -|-            -|--------------|",
                "|              |              |                             |              |",
                "|              |    Castle    |                             |   Twisted    |",
                "|              |    Cellar    |                             |    Caves     |",
                "|              |              |                             |              |",
                "|----[X][X]----|--------------|--------------|-            -|-            -|",
                "|                                                           |              |",
                "|    Castle              [Duskwood Forest]                 [X]   Tilled    |",
                "|   Courtyard                                              [X]   Plains    |",
                "|                                                           |              |",
                "|--------------|-            -|--------------|-            -|-            -|",
                "|//////////////|                             |              |              |",
                "|///Endless////|                   Wolves    |              |     Old      |",
                "|//// Fog//////|                    Den      |              |     Town     |",
                "|//////////////|                             |              |              |",
                "|--------------|--------------|--------------|--------------|--------------|");
    }

    public static String c3Map() {
        return String.join("\n", "                             Hero's Map                                     ",
                "|--------------|--------------|--------------|--------------|--------------|",
                "|              |              |                             |              |",
                "|    Castle                  [X]   [The Counts Chamber]        The Throne  |",
                "|    Armoury                 [X]                                  Room     |",
                "|              |              |                             |              |",
                "|--------------|-            -|--------------|--------------|--------------|",
                "|                             |              |              |//////////////|",
                "|    [Castle Sinistraad]      |   Duskwood   |    Mystic    |////Twisted///|",
                "|                             |   Clearing   |    Lake      |///Mountains//|",
                "|                             |              |              |//////////////|",
                "|-            -|----      ----|-            -|-            -|--------------|",
                "|              |              |                             |              |",
                "|              |    Castle    |                             |   Twisted    |",
                "|              |    Cellar    |                             |    Caves     |",
                "|              |              |<You Are Here>               |              |",
                "|----[X][X]----|--------------|--------------|-            -|-            -|",
                "|                                                           |              |",
                "|    Castle              [Duskwood Forest]                 [X]   Tilled    |",
                "|   Courtyard                                              [X]   Plains    |",
                "|                                                           |              |",
                "|--------------|-            -|--------------|-            -|-            -|",
                "|//////////////|                             |              |              |",
                "|///Endless////|                   Wolves    |              |     Old      |",
                "|//// Fog//////|                    Den      |              |     Town     |",
                "|//////////////|                             |              |              |",
                "|--------------|--------------|--------------|--------------|--------------|");
    }

    public static String c4Map() {
        return String.join("\n", "                             Hero's Map                                     ",
                "|--------------|--------------|--------------|--------------|--------------|",
                "|              |              |                             |              |",
                "|    Castle                  [X]   [The Counts Chamber]        The Throne  |",
                "|    Armoury                 [X]                                  Room     |",
                "|              |              |                             |              |",
                "|--------------|-            -|--------------|--------------|--------------|",
                "|                             |              |              |//////////////|",
                "|    [Castle Sinistraad]      |   Duskwood   |    Mystic    |////Twisted///|",
                "|                             |   Clearing   |    Lake      |///Mountains//|",
                "|                             |              |              |//////////////|",
                "|-            -|----      ----|-            -|-            -|--------------|",
                "|              |              |                             |              |",
                "|              |    Castle    |                             |   Twisted    |",
                "|              |    Cellar    |                             |    Caves     |",
                "|              |              |                             |              |",
                "|----[X][X]----|--------------|--------------|-            -|-            -|",
                "|                                                           |              |",
                "|    Castle              [Duskwood Forest]                 [X]   Tilled    |",
                "|   Courtyard                                              [X]   Plains    |",
                "|                              <You Are Here>               |              |",
                "|--------------|-            -|--------------|-            -|-            -|",
                "|//////////////|                             |              |              |",
                "|///Endless////|                   Wolves    |              |     Old      |",
                "|//// Fog//////|                    Den      |              |     Town     |",
                "|//////////////|                             |              |              |",
                "|--------------|--------------|--------------|--------------|--------------|");
    }

    public static String c5Map() {
        return String.join("\n", "                             Hero's Map                                     ",
                "|--------------|--------------|--------------|--------------|--------------|",
                "|              |              |                             |              |",
                "|    Castle                  [X]   [The Counts Chamber]        The Throne  |",
                "|    Armoury                 [X]                                  Room     |",
                "|              |              |                             |              |",
                "|--------------|-            -|--------------|--------------|--------------|",
                "|                             |              |              |//////////////|",
                "|    [Castle Sinistraad]      |   Duskwood   |    Mystic    |////Twisted///|",
                "|                             |   Clearing   |    Lake      |///Mountains//|",
                "|                             |              |              |//////////////|",
                "|-            -|----      ----|-            -|-            -|--------------|",
                "|              |              |                             |              |",
                "|              |    Castle    |                             |   Twisted    |",
                "|              |    Cellar    |                             |    Caves     |",
                "|              |              |                             |              |",
                "|----[X][X]----|--------------|--------------|-            -|-            -|",
                "|                                                           |              |",
                "|    Castle              [Duskwood Forest]                 [X]   Tilled    |",
                "|   Courtyard                                              [X]   Plains    |",
                "|                                                           |              |",
                "|--------------|-            -|--------------|-            -|-            -|",
                "|//////////////|                             |              |              |",
                "|///Endless////|                   Wolves    |              |     Old      |",
                "|//// Fog//////|                    Den      |              |     Town     |",
                "|//////////////|               <You Are Here>|              |              |",
                "|--------------|--------------|--------------|--------------|--------------|");
    }

    public static String d1Map() {
        return String.join("\n", "                             Hero's Map                                     ",
                "|--------------|--------------|--------------|--------------|--------------|",
                "|              |              |                             |              |",
                "|    Castle                  [X]   [The Counts Chamber]        The Throne  |",
                "|    Armoury                 [X]                                  Room     |",
                "|              |              |               <You Are Here>|              |",
                "|--------------|-            -|--------------|--------------|--------------|",
                "|                             |              |              |//////////////|",
                "|    [Castle Sinistraad]      |   Duskwood   |    Mystic    |////Twisted///|",
                "|                             |   Clearing   |    Lake      |///Mountains//|",
                "|                             |              |              |//////////////|",
                "|-            -|----      ----|-            -|-            -|--------------|",
                "|              |              |                             |              |",
                "|              |    Castle    |                             |   Twisted    |",
                "|              |    Cellar    |                             |    Caves     |",
                "|              |              |                             |              |",
                "|----[X][X]----|--------------|--------------|-            -|-            -|",
                "|                                                           |              |",
                "|    Castle              [Duskwood Forest]                 [X]   Tilled    |",
                "|   Courtyard                                              [X]   Plains    |",
                "|                                                           |              |",
                "|--------------|-            -|--------------|-            -|-            -|",
                "|//////////////|                             |              |              |",
                "|///Endless////|                   Wolves    |              |     Old      |",
                "|//// Fog//////|                    Den      |              |     Town     |",
                "|//////////////|                             |              |              |",
                "|--------------|--------------|--------------|--------------|--------------|");
    }

    public static String d2Map() {
        return String.join("\n", "                             Hero's Map                                     ",
                "|--------------|--------------|--------------|--------------|--------------|",
                "|              |              |                             |              |",
                "|    Castle                  [X]   [The Counts Chamber]        The Throne  |",
                "|    Armoury                 [X]                                  Room     |",
                "|              |              |                             |              |",
                "|--------------|-            -|--------------|--------------|--------------|",
                "|                             |              |              |//////////////|",
                "|    [Castle Sinistraad]      |   Duskwood   |    Mystic    |////Twisted///|",
                "|                             |   Clearing   |    Lake      |///Mountains//|",
                "|                             |              |<You Are Here>|//////////////|",
                "|-            -|----      ----|-            -|-            -|--------------|",
                "|              |              |                             |              |",
                "|              |    Castle    |                             |   Twisted    |",
                "|              |    Cellar    |                             |    Caves     |",
                "|              |              |                             |              |",
                "|----[X][X]----|--------------|--------------|-            -|-            -|",
                "|                                                           |              |",
                "|    Castle              [Duskwood Forest]                 [X]   Tilled    |",
                "|   Courtyard                                              [X]   Plains    |",
                "|                                                           |              |",
                "|--------------|-            -|--------------|-            -|-            -|",
                "|//////////////|                             |              |              |",
                "|///Endless////|                   Wolves    |              |     Old      |",
                "|//// Fog//////|                    Den      |              |     Town     |",
                "|//////////////|                             |              |              |",
                "|--------------|--------------|--------------|--------------|--------------|");
    }

    public static String d3Map() {
        return String.join("\n", "                             Hero's Map                                     ",
                "|--------------|--------------|--------------|--------------|--------------|",
                "|              |              |                             |              |",
                "|    Castle                  [X]   [The Counts Chamber]        The Throne  |",
                "|    Armoury                 [X]                                  Room     |",
                "|              |              |                             |              |",
                "|--------------|-            -|--------------|--------------|--------------|",
                "|                             |              |              |//////////////|",
                "|    [Castle Sinistraad]      |   Duskwood   |    Mystic    |////Twisted///|",
                "|                             |   Clearing   |    Lake      |///Mountains//|",
                "|                             |              |              |//////////////|",
                "|-            -|----      ----|-            -|-            -|--------------|",
                "|              |              |                             |              |",
                "|              |    Castle    |                             |   Twisted    |",
                "|              |    Cellar    |                             |    Caves     |",
                "|              |              |               <You Are Here>|              |",
                "|----[X][X]----|--------------|--------------|-            -|-            -|",
                "|                                                           |              |",
                "|    Castle              [Duskwood Forest]                 [X]   Tilled    |",
                "|   Courtyard                                              [X]   Plains    |",
                "|                                                           |              |",
                "|--------------|-            -|--------------|-            -|-            -|",
                "|//////////////|                             |              |              |",
                "|///Endless////|                   Wolves    |              |     Old      |",
                "|//// Fog//////|                    Den      |              |     Town     |",
                "|//////////////|                             |              |              |",
                "|--------------|--------------|--------------|--------------|--------------|");
    }

    public static String d4Map() {
        return String.join("\n", "                             Hero's Map                                     ",
                "|--------------|--------------|--------------|--------------|--------------|",
                "|              |              |                             |              |",
                "|    Castle                  [X]   [The Counts Chamber]        The Throne  |",
                "|    Armoury                 [X]                                  Room     |",
                "|              |              |                             |              |",
                "|--------------|-            -|--------------|--------------|--------------|",
                "|                             |              |              |//////////////|",
                "|    [Castle Sinistraad]      |   Duskwood   |    Mystic    |////Twisted///|",
                "|                             |   Clearing   |    Lake      |///Mountains//|",
                "|                             |              |              |//////////////|",
                "|-            -|----      ----|-            -|-            -|--------------|",
                "|              |              |                             |              |",
                "|              |    Castle    |                             |   Twisted    |",
                "|              |    Cellar    |                             |    Caves     |",
                "|              |              |                             |              |",
                "|----[X][X]----|--------------|--------------|-            -|-            -|",
                "|                                                           |              |",
                "|    Castle              [Duskwood Forest]                 [X]   Tilled    |",
                "|   Courtyard                                              [X]   Plains    |",
                "|                                             <You Are Here>|              |",
                "|--------------|-            -|--------------|-            -|-            -|",
                "|//////////////|                             |              |              |",
                "|///Endless////|                   Wolves    |              |     Old      |",
                "|//// Fog//////|                    Den      |              |     Town     |",
                "|//////////////|                             |              |              |",
                "|--------------|--------------|--------------|--------------|--------------|");
    }

    public static String d5Map() {
        return String.join("\n", "                             Hero's Map                                     ",
                "|--------------|--------------|--------------|--------------|--------------|",
                "|              |              |                             |              |",
                "|    Castle                  [X]   [The Counts Chamber]        The Throne  |",
                "|    Armoury                 [X]                                  Room     |",
                "|              |              |                             |              |",
                "|--------------|-            -|--------------|--------------|--------------|",
                "|                             |              |              |//////////////|",
                "|    [Castle Sinistraad]      |   Duskwood   |    Mystic    |////Twisted///|",
                "|                             |   Clearing   |    Lake      |///Mountains//|",
                "|                             |              |              |//////////////|",
                "|-            -|----      ----|-            -|-            -|--------------|",
                "|              |              |                             |              |",
                "|              |    Castle    |                             |   Twisted    |",
                "|              |    Cellar    |                             |    Caves     |",
                "|              |              |                             |              |",
                "|----[X][X]----|--------------|--------------|-            -|-            -|",
                "|                                                           |              |",
                "|    Castle              [Duskwood Forest]                 [X]   Tilled    |",
                "|   Courtyard                                              [X]   Plains    |",
                "|                                                           |              |",
                "|--------------|-            -|--------------|-            -|-            -|",
                "|//////////////|                             |              |              |",
                "|///Endless////|                   Wolves    |              |     Old      |",
                "|//// Fog//////|                    Den      |              |     Town     |",
                "|//////////////|                             |<You Are Here>|              |",
                "|--------------|--------------|--------------|--------------|--------------|");
    }

    public static String e1Map() {
        return String.join("\n", "                             Hero's Map                                     ",
                "|--------------|--------------|--------------|--------------|--------------|",
                "|              |              |                             |              |",
                "|    Castle                  [X]   [The Counts Chamber]        The Throne  |",
                "|    Armoury                 [X]                                  Room     |",
                "|              |              |                             |<You Are Here>|",
                "|--------------|-            -|--------------|--------------|--------------|",
                "|                             |              |              |//////////////|",
                "|    [Castle Sinistraad]      |   Duskwood   |    Mystic    |////Twisted///|",
                "|                             |   Clearing   |    Lake      |///Mountains//|",
                "|                             |              |              |//////////////|",
                "|-            -|----      ----|-            -|-            -|--------------|",
                "|              |              |                             |              |",
                "|              |    Castle    |                             |   Twisted    |",
                "|              |    Cellar    |                             |    Caves     |",
                "|              |              |                             |              |",
                "|----[X][X]----|--------------|--------------|-            -|-            -|",
                "|                                                           |              |",
                "|    Castle              [Duskwood Forest]                 [X]   Tilled    |",
                "|   Courtyard                                              [X]   Plains    |",
                "|                                                           |              |",
                "|--------------|-            -|--------------|-            -|-            -|",
                "|//////////////|                             |              |              |",
                "|///Endless////|                   Wolves    |              |     Old      |",
                "|//// Fog//////|                    Den      |              |     Town     |",
                "|//////////////|                             |              |              |",
                "|--------------|--------------|--------------|--------------|--------------|");
    }

    public static String e3Map() {
        return String.join("\n", "                             Hero's Map                                     ",
                "|--------------|--------------|--------------|--------------|--------------|",
                "|              |              |                             |              |",
                "|    Castle                  [X]   [The Counts Chamber]        The Throne  |",
                "|    Armoury                 [X]                                  Room     |",
                "|              |              |                             |              |",
                "|--------------|-            -|--------------|--------------|--------------|",
                "|                             |              |              |//////////////|",
                "|    [Castle Sinistraad]      |   Duskwood   |    Mystic    |////Twisted///|",
                "|                             |   Clearing   |    Lake      |///Mountains//|",
                "|                             |              |              |//////////////|",
                "|-            -|----      ----|-            -|-            -|--------------|",
                "|              |              |                             |              |",
                "|              |    Castle    |                             |   Twisted    |",
                "|              |    Cellar    |                             |    Caves     |",
                "|              |              |                             |<You Are Here>|",
                "|----[X][X]----|--------------|--------------|-            -|-            -|",
                "|                                                           |              |",
                "|    Castle              [Duskwood Forest]                 [X]   Tilled    |",
                "|   Courtyard                                              [X]   Plains    |",
                "|                                                           |              |",
                "|--------------|-            -|--------------|-            -|-            -|",
                "|//////////////|                             |              |              |",
                "|///Endless////|                   Wolves    |              |     Old      |",
                "|//// Fog//////|                    Den      |              |     Town     |",
                "|//////////////|                             |              |              |",
                "|--------------|--------------|--------------|--------------|--------------|");
    }

    public static String e4Map() {
        return String.join("\n", "                             Hero's Map                                     ",
                "|--------------|--------------|--------------|--------------|--------------|",
                "|              |              |                             |              |",
                "|    Castle                  [X]   [The Counts Chamber]        The Throne  |",
                "|    Armoury                 [X]                                  Room     |",
                "|              |              |                             |              |",
                "|--------------|-            -|--------------|--------------|--------------|",
                "|                             |              |              |//////////////|",
                "|    [Castle Sinistraad]      |   Duskwood   |    Mystic    |////Twisted///|",
                "|                             |   Clearing   |    Lake      |///Mountains//|",
                "|                             |              |              |//////////////|",
                "|-            -|----      ----|-            -|-            -|--------------|",
                "|              |              |                             |              |",
                "|              |    Castle    |                             |   Twisted    |",
                "|              |    Cellar    |                             |    Caves     |",
                "|              |              |                             |              |",
                "|----[X][X]----|--------------|--------------|-            -|-            -|",
                "|                                                           |              |",
                "|    Castle              [Duskwood Forest]                 [X]   Tilled    |",
                "|   Courtyard                                              [X]   Plains    |",
                "|                                                           |<You Are Here>|",
                "|--------------|-            -|--------------|-            -|-            -|",
                "|//////////////|                             |              |              |",
                "|///Endless////|                   Wolves    |              |     Old      |",
                "|//// Fog//////|                    Den      |              |     Town     |",
                "|//////////////|                             |              |              |",
                "|--------------|--------------|--------------|--------------|--------------|");
    }

    public static String e5Map() {
        return String.join("\n", "                             Hero's Map                                     ",
                "|--------------|--------------|--------------|--------------|--------------|",
                "|              |              |                             |              |",
                "|    Castle                  [X]   [The Counts Chamber]        The Throne  |",
                "|    Armoury                 [X]                                  Room     |",
                "|              |              |                             |              |",
                "|--------------|-            -|--------------|--------------|--------------|",
                "|                             |              |              |//////////////|",
                "|    [Castle Sinistraad]      |   Duskwood   |    Mystic    |////Twisted///|",
                "|                             |   Clearing   |    Lake      |///Mountains//|",
                "|                             |              |              |//////////////|",
                "|-            -|----      ----|-            -|-            -|--------------|",
                "|              |              |                             |              |",
                "|              |    Castle    |                             |   Twisted    |",
                "|              |    Cellar    |                             |    Caves     |",
                "|              |              |                             |              |",
                "|----[X][X]----|--------------|--------------|-            -|-            -|",
                "|                                                           |              |",
                "|    Castle              [Duskwood Forest]                 [X]   Tilled    |",
                "|   Courtyard                                              [X]   Plains    |",
                "|                                                           |              |",
                "|--------------|-            -|--------------|-            -|-            -|",
                "|//////////////|                             |              |              |",
                "|///Endless////|                   Wolves    |              |     Old      |",
                "|//// Fog//////|                    Den      |              |     Town     |",
                "|//////////////|                             |              |<You Are Here>|",
                "|--------------|--------------|--------------|--------------|--------------|");
    }
}
